### ISSUE TITLE
Perfomance on CPU

### ISSUE THREAD

**Issue by pauloamed** [bobetocalo/bobetocalo_eccv18#5]
Hi! First of all, congratulations on your work!

From your paper: "At runtime our method process test images on average at a rate of 32 FPS". Is this performance using only the "Intel Xeon E5-1650" or also the GPU?

**Comment by bobetocalo** [comment]
We use the GPU to estimate the heatmaps which is the bottleneck. We use the CPU multi-threaded to compute our coarse-to-fine ERT second stage.

Kind regards,
Roberto Valle
